services:
  app:
    build: .
    restart: always
    expose:
      - "8080"

  npm:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    depends_on:
      - app

volumes:
  npm_data:
  npm_letsencrypt: